export var mockApi = {
  currentPanel: "content",
  subjectTitle: "",
  subjectContent: "",
  imageDescription: "",
  linkDescription: "", 
  linkContent: "",
  titleIsErrored: false,
  contentIsErrored: false,
  updateSubjectTitle: () => {},
  updateSubjectContent: () => {},
  updateImageDescription: () => {},
  updateLinkDescription: () => {},
  updateLinkContent: () => {},
};