export const mockApi = {
  nameValue: "",
  usernameValue: "",
  firstEmailValue: "",
  secondEmailValue: "",
  firstPasswordValue: "",
  secondPasswordValue: "",
  locationValue: "",
  listOpen: false,
  dropDownIsErrored: false,
  selectedLocation: "",
  selectedAvatar: null,
  isSignUp: false,
  toggleList: () => {},
  updateNameValue: () => {},
  updateUsernameValue: () => {},
  updateEmailValue: () => {},
  updateLocationValue: () => {},
  updatePasswordValue: () => {},
  onLocationSelected: () => {},
  onClickAv: () => {},
  toggleSignUp: () => {},
  resetDropdown: () => {},
  resetAll: () => {},
  submit: () => {}
};
