export const mockApi = {
  nameValue: "",
  usernameValue: "",
  emailValue: "",
  passwordValue: "",
  locationValue: "",
  listOpen: false,
  dropDownIsErrored: false,
  selectedLocation: "",
  selectedAvatar: null,
  toggleList: () => {},
  updateNameValue: () => {},
  updateUsernameValue: () => {},
  updateEmailValue: () => {},
  updateLocationValue: () => {},
  updatePasswordValue: () => {},
  onLocationSelected: () => {},
  onClickAv: () => {},
  toggleSignUp: () => {},
  resetDropdown: () => {},
  isSignUp: () => {},
  resetAll: () => {},
  submit: () => {}
};
