export const mockApi = {
  firstNameValue: "",
  lastNameValue: "",
  usernameValue: "",
  firstEmailValue: "",
  secondEmailValue: "",
  locationValue: "",
  firstPasswordValue: "",
  secondPasswordValue: "",
  selectedLocation: null,
  emailsMatch: null,
  passwordsMatch: null,
  listOpen: false,
  selectedAvatar: null,
  isSignUp: showSignUp,
  firstNameInputIsErrored: false,
  lastNameInputIsErrored: false,
  usernameInputIsErrored: false,
  emailInputIsErrored: false,
  locationInputIsErrored: false,
  passwordInputIsErrored: false,
  avatarInputIsErrored: false,
  toggleList: () => {},
  updateNameValue: () => {},
  updateUsernameValue: () => {},
  updateEmailValue: () => {},
  updateLocationValue: () => {},
  updatePasswordValue: () => {},
  onLocationSelected: () => {},
  onClickAv: () => {},
  toggleSignUp: () => {},
  resetDropdown: () => {},
  resetAll: () => {},
  submit: () => {}
};
