import PropTypes from "prop-types";

export const SignUpInCardApiPropTypes = PropTypes.shape({
  firstNameValue: PropTypes.string.isRequired,
  lastNameValue: PropTypes.string.isRequired,
  usernameValue: PropTypes.string.isRequired,
  emailValue: PropTypes.string.isRequired,
  passwordValue: PropTypes.string.isRequired,
  locationValue: PropTypes.string.isRequired,
  listOpen: PropTypes.bool.isRequired,
  selectedLocation: PropTypes.object,
  selectedAvatar: PropTypes.string,
  firstNameInputIsErrored: PropTypes.bool.isRequired,
  lastNameInputIsErrored: PropTypes.bool.isRequired,
  usernameInputIsErrored: PropTypes.bool.isRequired,
  emailInputIsErrored: PropTypes.bool.isRequired,
  locationInputIsErrored: PropTypes.bool.isRequired,
  passwordInputIsErrored: PropTypes.bool.isRequired,
  avatarInputIsErrored: PropTypes.bool.isRequired,
  toggleList: PropTypes.func.isRequired,
  updateFirstNameValue: PropTypes.func.isRequired,
  updateLastNameValue: PropTypes.func.isRequired,
  updateUsernameValue: PropTypes.func.isRequired,
  updateEmailValue: PropTypes.func.isRequired,
  updateLocationValue: PropTypes.func.isRequired,
  updatePasswordValue: PropTypes.func.isRequired,
  onLocationSelected: PropTypes.func.isRequired,
  onClickAv: PropTypes.func.isRequired,
  toggleSignUp: PropTypes.func.isRequired,
  resetDropdown: PropTypes.func.isRequired,
  isSignUp: PropTypes.func.isRequired,
  resetAll: PropTypes.func.isRequired,
  locationNotFound: PropTypes.func.isRequired,
  submit: PropTypes.func.isRequired
});
